Better `doge#install()`
kkoomen/vim-doge pull request #153
Opened 2020-11-10 16:24 UTC by subnut

# Prelude

Thank you for helping out DoGe!

By contributing to DoGe you agree to the following statements:

- [x] I have read and understood the [Contribution Guidelines](https://github.com/kkoomen/vim-doge/blob/master/CONTRIBUTING.md).
- [x] I have read and understood the [Code of Conduct](https://github.com/kkoomen/vim-doge/blob/master/CODE_OF_CONDUCT.md).

# Why this PR?

Please see the detailed commit messages

2020-11-11 07:52 UTC, subnut commented
Ping @kkoomen

2020-11-11 08:11 UTC, kkoomen commented
Thanks for your effort and +1 for the nice descriptions in the comments. I'll test it this weekend myself.

2020-11-11 08:13 UTC, kkoomen commented
@subnut Since you did fix something for Windows, do you know if it's possible to check whether the user has `pwsh.exe`, if so then use that, otherwise do a fallback to `powershell.exe`. If you have any idea that feel free to submit another PR.

2020-11-11 08:34 UTC, subnut commented
@kkoomen Yep, it's easy. I am implementing it right away ... but can you please explain what is the advantage of `pwsh.exe` over the default `powershell.exe` ? 
I am actually not that familiar with PowerShell Core ....

2020-11-11 08:42 UTC, kkoomen commented
See [this comment](https://github.com/kkoomen/vim-doge/pull/108#issuecomment-721010001) in a previous discussion.

2020-11-11 08:52 UTC, subnut commented
@kkoomen Done!

2020-11-13 05:30 UTC, kkoomen approved these changes
I judged your code just on logic and styleguide. I haven't tested it yet, but I will do that this weekend somewhere.

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +      if a:2 == 0   " exitcode
Please remove unnecessary spaces:

```
 if a:2 == 0   " exitcode 
```

to

```
if a:2 == 0 " exitcode 
```

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +        call execute(s:terminal_bufnr . 'bd!')         " no errors to report, so delete buffer
I suggest to put this comment above the `call execute()` statement.

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +
This empty line can be deleted.

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +        call execute(s:terminal_bufnr . 'bd!')         " no errors to report, so delete buffer
I suggest to put this comment above the `call execute()` statement.

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +
This empty line can be deleted.

2020-11-13 05:30 UTC, kkoomen commented on scripts/install.sh
> +  echo "Please ensure curl is installed on the system and is available in the PATH" >&2
I suggest to use the following message: `Please make sure that curl is installed and available in your $PATH`

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +      echom 'vim-doge installed sucessfully'
Message standards from the plugin are always prefixed with `[DoGe]`, to follow this standard I suggest you use `echom '[DoGe] installed successfully'`

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +      echom 'vim-doge could not be installed ' . '(exit code: ' . a:exitcode . ')'
Message standards from the plugin are always prefixed with `[DoGe]`, to follow this standard I suggest you use `echom '[DoGe] installation failed: .....'`

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +  func! s:report_result(exitcode) abort
Please use `function!` and `endfunction` instead of abbreviations to abide by the plugin's standards.

2020-11-13 05:30 UTC, kkoomen commented on autoload/doge.vim
> +    " to show download progress bar, directly run execute()
Since this is quite a long explanation it's recommended to use a capital letter and dot at the end of the sentence. I suggest you use something like:

```
" Neovim does not output any stdout if it's called with :call execute(), therefore to show the download progress bar, we just call execute() by itself.
```

**NOTE**: Make sure to wrap at the 80th column.

2020-11-13 05:36 UTC, kkoomen requested changes
I submitted the previous wrong, as I do require changes.

2020-11-13 12:59 UTC, subnut commented on scripts/install.sh
> +  echo "Please ensure curl is installed on the system and is available in the PATH" >&2
Why `make sure` instead of `ensure`?
In my opinion, both convey the same meaning, but the latter seems more proper

2020-11-13 13:17 UTC, kkoomen commented on scripts/install.sh
> +  echo "Please ensure curl is installed on the system and is available in the PATH" >&2
Just feel more native and a bit more colloquial.

2020-11-13 13:20 UTC, kkoomen requested changes

2020-11-13 13:20 UTC, kkoomen commented on scripts/install.sh
> +  echo 'Please make sure curl is installed on the system and is available in the $PATH' >&2
You didn't copy my suggestion from before. I did remove `on the system` because it sounds weird and is redundant. Please remove it from the message.

2020-11-13 13:32 UTC, subnut commented on scripts/install.sh
> +  echo 'Please make sure curl is installed on the system and is available in the $PATH' >&2
Oops.. sorry!

2020-11-13 13:36 UTC, subnut commented on scripts/install.sh
> +  echo 'Please make sure curl is installed on the system and is available in the $PATH' >&2
Fixed.

2020-11-13 13:46 UTC, kkoomen commented
I just tested it but this doesn't work comfortably with tabs. You can add a check with `if &showtabline != 0 `. The problem is that I first run `:call doge#install()` and then while it's downloading, I am switching buffers. After that the stdout will appear double. See demo below

Also, the Linter failed in your last commit. See [details](https://github.com/kkoomen/vim-doge/pull/153/checks?check_run_id=1396007751).

![vim-doge-install](https://user-images.githubusercontent.com/10693490/99078581-84f73080-25b6-11eb-80e2-810ad98308f7.gif)

2020-11-13 14:01 UTC, subnut commented
Hmm... I can't reproduce your problem. Can you please give me a minimal .vimrc?

2020-11-13 14:38 UTC, kkoomen commented
Use this minimal vimrc:

```vim
set nocompatible
set runtimepath^=/path/to/vim-doge
filetype plugin indent on
syntax on
set hidden
set showtabline=2
```

then `vim -u vim-doge.vimrc` and then do the following:
- run `:call doge#install()`
- presss <kbd>Ctrl</kbd> + <kbd>w</kbd> + <kbd>ArrowDown</kbd>
- run `:bprev`

2020-11-13 15:14 UTC, subnut commented
Thanks, those repro steps helped a lot!

Should be fixed in the latest commit. Please check.

2020-11-13 15:19 UTC, kkoomen commented
Tested it. Works really well! How does this work on Windows? I don't run Windows myself. Can you send a GIF or another type of visual demo to show this behavior?

2020-11-13 15:33 UTC, subnut commented
Here you go -

![gifcast_201113210104](https://user-images.githubusercontent.com/56714626/99089626-901c8180-25f3-11eb-88f7-9df3026a0e0b.gif)

2020-11-13 15:36 UTC, kkoomen commented
That looks clean. I like it. One thing, if possible, can you add some kind of text while it's preparing the download? So when you run `:call doge#install()` it's preparing the download and basically shows you an empty terminal for roughly 5 seconds. Can we output some text like: `Preparing to download vim-doge binary...` ?

2020-11-13 15:44 UTC, subnut commented
Like so .... ? (See GIF)
![gifcast_201113211038](https://user-images.githubusercontent.com/56714626/99090919-31f09e00-25f5-11eb-9991-4be8a185ce22.gif)

2020-11-13 15:45 UTC, kkoomen commented
Perfect! If you push now then I'll merge tomorrow morning, since it's late here.

2020-11-14 00:28 UTC, kkoomen approved these changes

2020-11-14 00:34 UTC, merged

2020-11-14 00:35 UTC, kkoomen commented
This feature will be released in the upcoming version [v3.6.0](https://github.com/kkoomen/vim-doge/tree/v3.6.0).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

2020-11-14 02:44 UTC, subnut commented
> I can tell that your git commit hooks didn't trigger due to this.

I think there are no hooks...
![image](https://user-images.githubusercontent.com/56714626/99137514-4f535580-2651-11eb-901c-5326165f08f5.png)

2020-11-14 10:50 UTC, kkoomen commented
Just make sure you run `npm install` before developing.