Add omit_redundant_param_types option to the javascript generator.
kkoomen/vim-doge pull request #235
Opened 2021-02-01 06:57 UTC by vantreeseba

- [x] I have read and understood the [Contribution Guidelines](https://github.com/kkoomen/vim-doge/blob/master/CONTRIBUTING.md).
- [x] I have read and understood the [Code of Conduct](https://github.com/kkoomen/vim-doge/blob/master/CODE_OF_CONDUCT.md).

# Why this PR?

This would close issue #68.

It also makes the JSDoc work basically perfectly for haxe as well as typescript.

2021-02-02 01:03 UTC, vantreeseba commented
@kkoomen
Whenever you have some time, I couldn't get the tests to run locally (also I will make another commit with better naming / etc on the test), could you let me know if I am running the tests locally incorrectly?

I see there is a scripts/run-vader-tests.sh and I ran that as
```
./scripts/run-vader-tests.sh vim
```

But it just hung, is there something else I should be doing / need installed to so that I can attempt to clean this PR up and get it to the point where it is acceptable?

2021-02-02 01:35 UTC, kkoomen commented
@vantreeseba I don't think it's stuck. It just takes a damn long time to finish. Anyway, you can install the vim plugin Vader locally and then open the test file and run `:Vader` in there. That will be the quickest way to test your own file.

2021-02-02 01:45 UTC, kkoomen requested changes

2021-02-02 01:45 UTC, kkoomen commented on README.md
> +- `omit_redundant_param_types`: Whether or not to omit the `{Type}` part of
- Please use `{type}` where the first letter is lowercase.

2021-02-02 01:45 UTC, kkoomen commented on test/filetypes/javascript/functions.vader
> +Given javascript (functions with type information):
Please use the following description:

`functions where the type should be omitted if let g:doge_javascript_settings = {'omit_redundant_param_types': 1} is set`

to make it easier to find this test in the whole series of tests.

2021-02-02 06:09 UTC, vantreeseba commented
Both of the requested changes should be implemented, and I did get vader working locally.

Thanks so much for the help.

2021-02-02 08:09 UTC, kkoomen requested changes

2021-02-02 08:09 UTC, kkoomen commented on autoload/doge/preprocessors/javascript.vim
> +          if(!empty(l:param['type']))
- Please add a space after `if`
- Remove the unnecessary parenthesis around `!empty()`

2021-02-02 08:12 UTC, kkoomen requested changes

2021-02-02 08:12 UTC, kkoomen commented on autoload/doge/preprocessors/javascript.vim
> +      let l:filtered_params = []
You can just remove this variable, as you don't use it, right?

2021-02-05 02:49 UTC, vantreeseba commented
I realized the behavior of the return types is not correct, I will add another test and get some more code in to correct this.

I.e. Currently, no matter what the return is hidden (when omit_redundant_param_types is true), but it should only be hiding the type template portion is the type is known.

2021-02-16 13:14 UTC, kkoomen commented
@vantreeseba Regarding that the `./scripts/run-vader-scripts.sh` is not working locally is because in the CI it does clone the vader inside the current directory instead of being a sibling of the current working directory. I'll try to fix this asap.

2021-03-30 03:08 UTC, kkoomen commented
@vantreeseba Please fix tests so I can merge this soon. I want to merge this ASAP.

2021-04-09 04:15 UTC, vantreeseba commented
Hmm, I'm not sure why these tests are failing, I ran vader on those files locally and it seems to be working fine.  If you have any insight into why they would be, let me know and I will correct it.

2021-04-09 04:41 UTC, kkoomen commented
@vantreeseba The way Vader works when you pass multiple tests is that it will use a single vim instance to run everything. If tests fail, but locally running `:Vader` on the single file that fails, but doesn't fail locally, then the problem is that a combination of previous tests + current test will make the current test fail.

I'll make some time to fix the tests, because it's a bit troublesome to debug this.

2021-04-26 07:15 UTC, VVKot commented
Hey @kkoomen / @vantreeseba, wonder if there was any progress here? Anything I can help with?

2021-04-26 08:37 UTC, kkoomen commented
@VVKot I have time this weekend, so I can try to fix this.

2021-04-28 15:30 UTC, kkoomen approved these changes

2021-04-28 16:01 UTC, merged

2021-04-28 16:29 UTC, kkoomen commented
This feature has been merged and released in [v3.10.0](https://github.com/kkoomen/vim-doge/tree/v3.10.0).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.